# Generated by Django 2.0 on 2017-12-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0003_auto_20171214_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='alters_data',
            new_name='date_add',
        ),
    ]
