# Generated by Django 2.0 on 2017-12-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0004_auto_20171214_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_add',
            new_name='date_added',
        ),
    ]
